# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/fTools/tools/frmRegPoints.ui'
#
# Created: Wed Jul 29 01:08:21 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(373, 485)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rdoBoundary = QtGui.QRadioButton(self.groupBox)
        self.rdoBoundary.setChecked(True)
        self.rdoBoundary.setObjectName(_fromUtf8("rdoBoundary"))
        self.gridLayout_2.addWidget(self.rdoBoundary, 0, 0, 1, 4)
        self.inShape = QtGui.QComboBox(self.groupBox)
        self.inShape.setObjectName(_fromUtf8("inShape"))
        self.gridLayout_2.addWidget(self.inShape, 1, 0, 1, 4)
        self.rdoCoordinates = QtGui.QRadioButton(self.groupBox)
        self.rdoCoordinates.setObjectName(_fromUtf8("rdoCoordinates"))
        self.gridLayout_2.addWidget(self.rdoCoordinates, 2, 0, 1, 4)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.xMin = QtGui.QLineEdit(self.groupBox)
        self.xMin.setEnabled(False)
        self.xMin.setObjectName(_fromUtf8("xMin"))
        self.gridLayout_2.addWidget(self.xMin, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 2, 1, 1)
        self.yMin = QtGui.QLineEdit(self.groupBox)
        self.yMin.setEnabled(False)
        self.yMin.setObjectName(_fromUtf8("yMin"))
        self.gridLayout_2.addWidget(self.yMin, 3, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.xMax = QtGui.QLineEdit(self.groupBox)
        self.xMax.setEnabled(False)
        self.xMax.setObjectName(_fromUtf8("xMax"))
        self.gridLayout_2.addWidget(self.xMax, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 2, 1, 1)
        self.yMax = QtGui.QLineEdit(self.groupBox)
        self.yMax.setEnabled(False)
        self.yMax.setObjectName(_fromUtf8("yMax"))
        self.gridLayout_2.addWidget(self.yMax, 4, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridBox = QtGui.QGroupBox(Dialog)
        self.gridBox.setObjectName(_fromUtf8("gridBox"))
        self.gridlayout = QtGui.QGridLayout(self.gridBox)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.rdoSpacing = QtGui.QRadioButton(self.gridBox)
        self.rdoSpacing.setChecked(True)
        self.rdoSpacing.setObjectName(_fromUtf8("rdoSpacing"))
        self.hboxlayout.addWidget(self.rdoSpacing)
        self.spnSpacing = QtGui.QDoubleSpinBox(self.gridBox)
        self.spnSpacing.setDecimals(4)
        self.spnSpacing.setMinimum(0.0001)
        self.spnSpacing.setMaximum(1000000000.0)
        self.spnSpacing.setSingleStep(0.0001)
        self.spnSpacing.setObjectName(_fromUtf8("spnSpacing"))
        self.hboxlayout.addWidget(self.spnSpacing)
        self.gridlayout.addLayout(self.hboxlayout, 0, 0, 1, 2)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.rdoNumber = QtGui.QRadioButton(self.gridBox)
        self.rdoNumber.setObjectName(_fromUtf8("rdoNumber"))
        self.hboxlayout1.addWidget(self.rdoNumber)
        self.spnNumber = QtGui.QSpinBox(self.gridBox)
        self.spnNumber.setEnabled(False)
        self.spnNumber.setMinimum(1)
        self.spnNumber.setMaximum(1000000000)
        self.spnNumber.setObjectName(_fromUtf8("spnNumber"))
        self.hboxlayout1.addWidget(self.spnNumber)
        self.gridlayout.addLayout(self.hboxlayout1, 1, 0, 1, 2)
        self.chkRandom = QtGui.QCheckBox(self.gridBox)
        self.chkRandom.setObjectName(_fromUtf8("chkRandom"))
        self.gridlayout.addWidget(self.chkRandom, 2, 0, 1, 2)
        self.spnInset = QtGui.QDoubleSpinBox(self.gridBox)
        self.spnInset.setDecimals(4)
        self.spnInset.setMaximum(9999.0)
        self.spnInset.setSingleStep(0.0001)
        self.spnInset.setObjectName(_fromUtf8("spnInset"))
        self.gridlayout.addWidget(self.spnInset, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridlayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.gridBox, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.outShape = QtGui.QLineEdit(Dialog)
        self.outShape.setReadOnly(True)
        self.outShape.setObjectName(_fromUtf8("outShape"))
        self.hboxlayout2.addWidget(self.outShape)
        self.toolOut = QtGui.QPushButton(Dialog)
        self.toolOut.setObjectName(_fromUtf8("toolOut"))
        self.hboxlayout2.addWidget(self.toolOut)
        self.gridLayout.addLayout(self.hboxlayout2, 3, 0, 1, 1)
        self.addToCanvasCheck = QtGui.QCheckBox(Dialog)
        self.addToCanvasCheck.setChecked(True)
        self.addToCanvasCheck.setObjectName(_fromUtf8("addToCanvasCheck"))
        self.gridLayout.addWidget(self.addToCanvasCheck, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.buttonBox_2 = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.horizontalLayout.addWidget(self.buttonBox_2)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.close)
        QtCore.QObject.connect(self.rdoBoundary, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.inShape.setEnabled)
        QtCore.QObject.connect(self.rdoCoordinates, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.xMin.setEnabled)
        QtCore.QObject.connect(self.rdoCoordinates, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.xMax.setEnabled)
        QtCore.QObject.connect(self.rdoCoordinates, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.yMin.setEnabled)
        QtCore.QObject.connect(self.rdoCoordinates, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.yMax.setEnabled)
        QtCore.QObject.connect(self.rdoSpacing, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spnSpacing.setEnabled)
        QtCore.QObject.connect(self.rdoNumber, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spnNumber.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Generate Regular Points", None))
        self.groupBox.setTitle(_translate("Dialog", "Area", None))
        self.rdoBoundary.setText(_translate("Dialog", "Input Boundary Layer", None))
        self.rdoCoordinates.setText(_translate("Dialog", "Input Coordinates", None))
        self.label.setText(_translate("Dialog", "X Min", None))
        self.label_4.setText(_translate("Dialog", "Y Min", None))
        self.label_3.setText(_translate("Dialog", "X Max", None))
        self.label_5.setText(_translate("Dialog", "Y Max", None))
        self.gridBox.setTitle(_translate("Dialog", "Grid Spacing", None))
        self.rdoSpacing.setText(_translate("Dialog", "Use this point spacing", None))
        self.rdoNumber.setText(_translate("Dialog", "Use this number of points", None))
        self.chkRandom.setText(_translate("Dialog", "Apply random offset to point spacing", None))
        self.label_6.setText(_translate("Dialog", "Initial inset from corner (LH side)", None))
        self.label_2.setText(_translate("Dialog", "Output Shapefile", None))
        self.toolOut.setText(_translate("Dialog", "Browse", None))
        self.addToCanvasCheck.setText(_translate("Dialog", "Add result to canvas", None))

