# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/fTools/tools/frmGeoprocessing.ui'
#
# Created: Wed Jul 29 01:08:21 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(422, 497)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.label_1 = QtGui.QLabel(Dialog)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.vboxlayout.addWidget(self.label_1)
        self.inShapeA = QtGui.QComboBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inShapeA.sizePolicy().hasHeightForWidth())
        self.inShapeA.setSizePolicy(sizePolicy)
        self.inShapeA.setObjectName(_fromUtf8("inShapeA"))
        self.vboxlayout.addWidget(self.inShapeA)
        self.gridLayout.addLayout(self.vboxlayout, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.useSelectedA = QtGui.QCheckBox(Dialog)
        self.useSelectedA.setObjectName(_fromUtf8("useSelectedA"))
        self.verticalLayout.addWidget(self.useSelectedA)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.vboxlayout1.addWidget(self.label_2)
        self.inShapeB = QtGui.QComboBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inShapeB.sizePolicy().hasHeightForWidth())
        self.inShapeB.setSizePolicy(sizePolicy)
        self.inShapeB.setObjectName(_fromUtf8("inShapeB"))
        self.vboxlayout1.addWidget(self.inShapeB)
        self.gridLayout.addLayout(self.vboxlayout1, 2, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.useSelectedB = QtGui.QCheckBox(Dialog)
        self.useSelectedB.setObjectName(_fromUtf8("useSelectedB"))
        self.verticalLayout_2.addWidget(self.useSelectedB)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblSegments = QtGui.QLabel(Dialog)
        self.lblSegments.setObjectName(_fromUtf8("lblSegments"))
        self.horizontalLayout.addWidget(self.lblSegments)
        self.spnSegments = QtGui.QSpinBox(Dialog)
        self.spnSegments.setMinimum(5)
        self.spnSegments.setProperty("value", 5)
        self.spnSegments.setObjectName(_fromUtf8("spnSegments"))
        self.horizontalLayout.addWidget(self.spnSegments)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.rdoBuffer = QtGui.QRadioButton(Dialog)
        self.rdoBuffer.setChecked(True)
        self.rdoBuffer.setObjectName(_fromUtf8("rdoBuffer"))
        self.hboxlayout1.addWidget(self.rdoBuffer)
        self.hboxlayout.addLayout(self.hboxlayout1)
        self.param = QtGui.QLineEdit(Dialog)
        self.param.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.param.sizePolicy().hasHeightForWidth())
        self.param.setSizePolicy(sizePolicy)
        self.param.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.param.setText(_fromUtf8(""))
        self.param.setCursorPosition(0)
        self.param.setObjectName(_fromUtf8("param"))
        self.hboxlayout.addWidget(self.param)
        self.gridLayout.addLayout(self.hboxlayout, 5, 0, 1, 1)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.rdoField = QtGui.QRadioButton(Dialog)
        self.rdoField.setObjectName(_fromUtf8("rdoField"))
        self.hboxlayout2.addWidget(self.rdoField)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.hboxlayout2.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem)
        self.vboxlayout2.addLayout(self.hboxlayout2)
        self.attrib = QtGui.QComboBox(Dialog)
        self.attrib.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attrib.sizePolicy().hasHeightForWidth())
        self.attrib.setSizePolicy(sizePolicy)
        self.attrib.setObjectName(_fromUtf8("attrib"))
        self.vboxlayout2.addWidget(self.attrib)
        self.gridLayout.addLayout(self.vboxlayout2, 6, 0, 1, 1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.mergeOutput = QtGui.QCheckBox(Dialog)
        self.mergeOutput.setEnabled(True)
        self.mergeOutput.setObjectName(_fromUtf8("mergeOutput"))
        self.hboxlayout3.addWidget(self.mergeOutput)
        self.gridLayout.addLayout(self.hboxlayout3, 7, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.vboxlayout3.addWidget(self.label_5)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.outShape = QtGui.QLineEdit(Dialog)
        self.outShape.setReadOnly(True)
        self.outShape.setObjectName(_fromUtf8("outShape"))
        self.hboxlayout4.addWidget(self.outShape)
        self.btnBrowse = QtGui.QPushButton(Dialog)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.hboxlayout4.addWidget(self.btnBrowse)
        self.vboxlayout3.addLayout(self.hboxlayout4)
        self.gridLayout.addLayout(self.vboxlayout3, 9, 0, 1, 1)
        self.addToCanvasCheck = QtGui.QCheckBox(Dialog)
        self.addToCanvasCheck.setChecked(True)
        self.addToCanvasCheck.setObjectName(_fromUtf8("addToCanvasCheck"))
        self.gridLayout.addWidget(self.addToCanvasCheck, 10, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.buttonBox_2 = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.horizontalLayout_2.addWidget(self.buttonBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 11, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.rdoField, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.attrib.setEnabled)
        QtCore.QObject.connect(self.rdoBuffer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.param.setEnabled)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Geoprocessing", None))
        self.label_1.setText(_translate("Dialog", "Input vector layer", None))
        self.useSelectedA.setText(_translate("Dialog", "Use only selected features", None))
        self.label_2.setText(_translate("Dialog", "Intersect layer", None))
        self.useSelectedB.setText(_translate("Dialog", "Use only selected features", None))
        self.lblSegments.setText(_translate("Dialog", "Segments to approximate", None))
        self.rdoBuffer.setText(_translate("Dialog", "Buffer distance", None))
        self.rdoField.setText(_translate("Dialog", "Buffer distance field", None))
        self.label_4.setText(_translate("Dialog", "Dissolve field", None))
        self.mergeOutput.setText(_translate("Dialog", "Dissolve buffer results", None))
        self.label_5.setText(_translate("Dialog", "Output shapefile", None))
        self.btnBrowse.setText(_translate("Dialog", "Browse", None))
        self.addToCanvasCheck.setText(_translate("Dialog", "Add result to canvas", None))

