# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/fTools/tools/frmRandPoints.ui'
#
# Created: Wed Jul 29 01:08:21 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(384, 470)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.inShape = QtGui.QComboBox(Dialog)
        self.inShape.setObjectName(_fromUtf8("inShape"))
        self.gridLayout.addWidget(self.inShape, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.rdoUnstratified = QtGui.QRadioButton(self.groupBox)
        self.rdoUnstratified.setChecked(True)
        self.rdoUnstratified.setObjectName(_fromUtf8("rdoUnstratified"))
        self.hboxlayout.addWidget(self.rdoUnstratified)
        self.spnUnstratified = QtGui.QSpinBox(self.groupBox)
        self.spnUnstratified.setEnabled(True)
        self.spnUnstratified.setMinimum(1)
        self.spnUnstratified.setMaximum(1000000)
        self.spnUnstratified.setObjectName(_fromUtf8("spnUnstratified"))
        self.hboxlayout.addWidget(self.spnUnstratified)
        self.gridlayout.addLayout(self.hboxlayout, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridlayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.rdoStratified = QtGui.QRadioButton(self.groupBox)
        self.rdoStratified.setObjectName(_fromUtf8("rdoStratified"))
        self.hboxlayout1.addWidget(self.rdoStratified)
        self.spnStratified = QtGui.QSpinBox(self.groupBox)
        self.spnStratified.setEnabled(False)
        self.spnStratified.setMinimum(1)
        self.spnStratified.setMaximum(1000000)
        self.spnStratified.setObjectName(_fromUtf8("spnStratified"))
        self.hboxlayout1.addWidget(self.spnStratified)
        self.gridlayout.addLayout(self.hboxlayout1, 3, 0, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.rdoDensity = QtGui.QRadioButton(self.groupBox)
        self.rdoDensity.setObjectName(_fromUtf8("rdoDensity"))
        self.hboxlayout2.addWidget(self.rdoDensity)
        self.spnDensity = QtGui.QDoubleSpinBox(self.groupBox)
        self.spnDensity.setEnabled(False)
        self.spnDensity.setDecimals(4)
        self.spnDensity.setMinimum(0.0001)
        self.spnDensity.setMaximum(9999.0)
        self.spnDensity.setSingleStep(0.0001)
        self.spnDensity.setProperty("value", 0.0001)
        self.spnDensity.setObjectName(_fromUtf8("spnDensity"))
        self.hboxlayout2.addWidget(self.spnDensity)
        self.gridlayout.addLayout(self.hboxlayout2, 4, 0, 1, 1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.rdoField = QtGui.QRadioButton(self.groupBox)
        self.rdoField.setObjectName(_fromUtf8("rdoField"))
        self.hboxlayout3.addWidget(self.rdoField)
        self.cmbField = QtGui.QComboBox(self.groupBox)
        self.cmbField.setEnabled(False)
        self.cmbField.setObjectName(_fromUtf8("cmbField"))
        self.hboxlayout3.addWidget(self.cmbField)
        self.gridlayout.addLayout(self.hboxlayout3, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.outShape = QtGui.QLineEdit(Dialog)
        self.outShape.setReadOnly(True)
        self.outShape.setObjectName(_fromUtf8("outShape"))
        self.hboxlayout4.addWidget(self.outShape)
        self.toolOut = QtGui.QPushButton(Dialog)
        self.toolOut.setObjectName(_fromUtf8("toolOut"))
        self.hboxlayout4.addWidget(self.toolOut)
        self.gridLayout.addLayout(self.hboxlayout4, 5, 0, 1, 1)
        self.addToCanvasCheck = QtGui.QCheckBox(Dialog)
        self.addToCanvasCheck.setChecked(True)
        self.addToCanvasCheck.setObjectName(_fromUtf8("addToCanvasCheck"))
        self.gridLayout.addWidget(self.addToCanvasCheck, 6, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.buttonBox_2 = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.horizontalLayout.addWidget(self.buttonBox_2)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.close)
        QtCore.QObject.connect(self.rdoUnstratified, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spnUnstratified.setEnabled)
        QtCore.QObject.connect(self.rdoStratified, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spnStratified.setEnabled)
        QtCore.QObject.connect(self.rdoField, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbField.setEnabled)
        QtCore.QObject.connect(self.rdoDensity, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spnDensity.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Generate Random Points", None))
        self.label_3.setText(_translate("Dialog", "Input Boundary Layer", None))
        self.groupBox.setTitle(_translate("Dialog", "Sample Size", None))
        self.label.setText(_translate("Dialog", "Unstratified Sampling Design (Entire layer)", None))
        self.rdoUnstratified.setText(_translate("Dialog", "Use this number of points", None))
        self.label_4.setText(_translate("Dialog", "Stratified Sampling Design (Individual polygons)", None))
        self.rdoStratified.setText(_translate("Dialog", "Use this number of points", None))
        self.rdoDensity.setText(_translate("Dialog", "Use this density of points", None))
        self.rdoField.setText(_translate("Dialog", "Use value from input field", None))
        self.label_2.setText(_translate("Dialog", "Output Shapefile", None))
        self.toolOut.setText(_translate("Dialog", "Browse", None))
        self.addToCanvasCheck.setText(_translate("Dialog", "Add result to canvas", None))

