# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/fTools/tools/frmSpatialJoin.ui'
#
# Created: Wed Jul 29 01:08:22 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(439, 525)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.vboxlayout.addWidget(self.label_3)
        self.inShape = QtGui.QComboBox(Dialog)
        self.inShape.setObjectName(_fromUtf8("inShape"))
        self.vboxlayout.addWidget(self.inShape)
        self.verticalLayout.addLayout(self.vboxlayout)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.vboxlayout1.addWidget(self.label)
        self.joinShape = QtGui.QComboBox(Dialog)
        self.joinShape.setObjectName(_fromUtf8("joinShape"))
        self.vboxlayout1.addWidget(self.joinShape)
        self.verticalLayout.addLayout(self.vboxlayout1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 2, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.chkMean = QtGui.QCheckBox(self.groupBox_2)
        self.chkMean.setEnabled(False)
        self.chkMean.setChecked(True)
        self.chkMean.setObjectName(_fromUtf8("chkMean"))
        self.gridlayout.addWidget(self.chkMean, 2, 1, 1, 1)
        self.rdoSummary = QtGui.QRadioButton(self.groupBox_2)
        self.rdoSummary.setObjectName(_fromUtf8("rdoSummary"))
        self.gridlayout.addWidget(self.rdoSummary, 1, 0, 1, 7)
        self.chkMin = QtGui.QCheckBox(self.groupBox_2)
        self.chkMin.setEnabled(False)
        self.chkMin.setObjectName(_fromUtf8("chkMin"))
        self.gridlayout.addWidget(self.chkMin, 2, 2, 1, 1)
        self.chkSum = QtGui.QCheckBox(self.groupBox_2)
        self.chkSum.setEnabled(False)
        self.chkSum.setObjectName(_fromUtf8("chkSum"))
        self.gridlayout.addWidget(self.chkSum, 2, 4, 1, 1)
        self.chkMedian = QtGui.QCheckBox(self.groupBox_2)
        self.chkMedian.setEnabled(False)
        self.chkMedian.setObjectName(_fromUtf8("chkMedian"))
        self.gridlayout.addWidget(self.chkMedian, 2, 5, 1, 1)
        self.chkMax = QtGui.QCheckBox(self.groupBox_2)
        self.chkMax.setEnabled(False)
        self.chkMax.setObjectName(_fromUtf8("chkMax"))
        self.gridlayout.addWidget(self.chkMax, 2, 3, 1, 1)
        self.rdoFirst = QtGui.QRadioButton(self.groupBox_2)
        self.rdoFirst.setChecked(True)
        self.rdoFirst.setObjectName(_fromUtf8("rdoFirst"))
        self.gridlayout.addWidget(self.rdoFirst, 0, 0, 1, 7)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.vboxlayout2.addWidget(self.label_2)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.outShape = QtGui.QLineEdit(Dialog)
        self.outShape.setReadOnly(True)
        self.outShape.setObjectName(_fromUtf8("outShape"))
        self.hboxlayout.addWidget(self.outShape)
        self.toolOut = QtGui.QPushButton(Dialog)
        self.toolOut.setObjectName(_fromUtf8("toolOut"))
        self.hboxlayout.addWidget(self.toolOut)
        self.vboxlayout2.addLayout(self.hboxlayout)
        self.verticalLayout.addLayout(self.vboxlayout2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox_3)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.rdoMatch = QtGui.QRadioButton(self.groupBox_3)
        self.rdoMatch.setChecked(True)
        self.rdoMatch.setObjectName(_fromUtf8("rdoMatch"))
        self.gridlayout1.addWidget(self.rdoMatch, 0, 0, 1, 1)
        self.rdoKeep = QtGui.QRadioButton(self.groupBox_3)
        self.rdoKeep.setObjectName(_fromUtf8("rdoKeep"))
        self.gridlayout1.addWidget(self.rdoKeep, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout.addWidget(self.progressBar)
        self.buttonBox_2 = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.horizontalLayout.addWidget(self.buttonBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.close)
        QtCore.QObject.connect(self.rdoSummary, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkMin.setEnabled)
        QtCore.QObject.connect(self.rdoSummary, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkMax.setEnabled)
        QtCore.QObject.connect(self.rdoSummary, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkSum.setEnabled)
        QtCore.QObject.connect(self.rdoSummary, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkMean.setEnabled)
        QtCore.QObject.connect(self.rdoSummary, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkMedian.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Spatial Join", None))
        self.label_3.setText(_translate("Dialog", "Target vector layer", None))
        self.label.setText(_translate("Dialog", "Join vector layer", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Attribute Summary", None))
        self.chkMean.setText(_translate("Dialog", "Mean", None))
        self.rdoSummary.setText(_translate("Dialog", "Take summary of intersecting features", None))
        self.chkMin.setText(_translate("Dialog", "Min", None))
        self.chkSum.setText(_translate("Dialog", "Sum", None))
        self.chkMedian.setText(_translate("Dialog", "Median", None))
        self.chkMax.setText(_translate("Dialog", "Max", None))
        self.rdoFirst.setText(_translate("Dialog", "Take attributes of first located feature", None))
        self.label_2.setText(_translate("Dialog", "Output Shapefile", None))
        self.toolOut.setText(_translate("Dialog", "Browse", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Output table", None))
        self.rdoMatch.setText(_translate("Dialog", "Only keep matching records", None))
        self.rdoKeep.setText(_translate("Dialog", "Keep all records (including non-matching target records)", None))

